//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManamentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enroll
    {
        public int stuId { get; set; }
        public int classId { get; set; }
        public string grade { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
